import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Arif',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Badhon',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Mens gray shirt',
      slug: 'Mens-gray-shirt',
      category: 'Shirts',
      image: '/images/p1.png', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '2',
      name: 'Mens black shirt',
      slug: 'Mens-black-shirt',
      category: 'Shirts',
      image: '/images/p2.png',
      price: 50,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '3',
      name: 'Womens purple dress',
      slug: 'Womens-purple-dress',
      category: 'dress',
      image: '/images/p3.png',
      price: 25,
      countInStock: 0,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '4',
      name: 'Womens red dress',
      slug: 'Womens-red-dress',
      category: 'dress',
      image: '/images/p4.png',
      price: 265,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '5',
      name: 'Womens black dress',
      slug: 'Womens-black-dress',
      category: 'dress',
      image: '/images/p5.png',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '6',
      name: 'Womens double dress',
      slug: 'Womens-double-dress',
      category: 'dress',
      image: '/images/p6.png',
      price: 605,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '7',
      name: 'Womens slim dress',
      slug: 'Womens-slim-dress',
      category: 'dress',
      image: '/images/p7.png',
      price: 650,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '8',
      name: 'Mens formal shirt',
      slug: 'Mens-formal-shirt',
      category: 'shirt',
      image: '/images/p8.png',
      price: 500,
      countInStock: 6,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 7,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '9',
      name: 'Mens blue shirt',
      slug: 'Mens-blue-shirt',
      category: 'shirt',
      image: '/images/p9.png',
      price: 625,
      countInStock: 9,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 7,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '10',
      name: 'Mens green shirt',
      slug: 'Mens-green-shirt',
      category: 'shirt',
      image: '/images/p10.png',
      price: 255,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '11',
      name: 'Mens half shirt',
      slug: 'Mens-half-shirt',
      category: 'shirt',
      image: '/images/p11.png',
      price: 300,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
    {
      // _id: '12',
      name: 'Womens gown dress',
      slug: 'Womens-gown-dress',
      category: 'dress',
      image: '/images/p12.png',
      price: 220,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 15,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    },
  ],
};
export default data;
